---
title: "contrast_pattern"
author: "Taewan Kim"
date: "3/16/2021"
output: html_document
---

```{r}
library(reshape2) # melt function
library(ggplot2) # ggplot function
library(pcaPP) # Fast Kendall function
library(energy) # Distance Correlation
library(Hmisc) # Hoeffding's D measure
library(entropy) # Mutual Information
library(minerva) # Maximum Information Coefficient
library(XICOR) # Chatterjee's Coefficient
library(dHSIC) # Hilbert Schmidt Independence Criterion
library(VineCopula) # Blomqvist's Beta

source("data_generation.R")
```

```{r}
generate_quadratic <- function(n){
  t(sapply(1:n, function(i){
    x <- stats::runif(1, min = -1, max = 1)
    y <- x^2
    c(x,y)
  }))
}

generate_quadratic2 <- function(n){
  t(sapply(1:n, function(i){
    x <- stats::runif(1, min = -1, max = 1)
    y <- x^2 + stats::rnorm(1, mean = 0, sd = 0.3)
    c(x,y)
  }))
}

gen_vertical1 <- function(n){
  t(sapply(1:n, function(i){
    x <- stats::runif(1, min = -2, max = 2)
    y <- 0 
    c(x,y)
  }))
}

gen_vertical2 <- function(n){
  t(sapply(1:n, function(i){
    x <- 0
    y <- stats::runif(1, min = -2, max = 2)
    c(x,y)
  }))
}

generate_power <- function(n){
  t(sapply(1:n, function(i){
    x <- stats::runif(1, min = 0, max = 2)
    y <- x^10 + stats::rnorm(1, mean = 10, sd = 10)
    c(x,y)
  }))
}

gen_linear <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    x <- stats::rnorm(1, mean = 2.5, sd = 1)
    y <- x + stats::rnorm(1, mean = 0, sd = 1)
    c(x,y)
  }))
}

gen_strong_linear <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    x <- stats::rnorm(1, mean = 2.5, sd = 1)
    y <- x + stats::rnorm(1, mean = 0, sd = 0.3)
    c(x,y)
  }))
}

gen_sine <- function(n){
  t(sapply(1:n, function(i){
    x <- stats::runif(1, min = -2, max = 12)
    y <- sin(x) + stats::rnorm(1, mean = 0, sd = 0.1)
    c(x,y)
  }))
}
```

```{r}
quadratic_1 <- generate_quadratic(100)
plot(quadratic_1)
```

```{r}
exper_n <- 500

ver1 <- gen_vertical1(exper_n)
plot(ver1)

ver2 <- gen_vertical2(exper_n)
plot(ver2)

cross <- rbind(ver1, ver2)
plot(cross)
```

```{r}
power <- generate_power(exper_n)
plot(power)
```

```{r}
quadratic2 <- generate_quadratic2(400)
plot(quadratic2)
```

```{r}
sine <- gen_sine(exper_n)
plot(sine)
```

## Dcor vs Pearson

```{r}
plot(quadratic_1)
```

```{r}
energy::dcor(quadratic_1[,1],quadratic_1[,2])
stats::cor(quadratic_1, method = "pearson")
#stats::cor(quadratic_1, method = "spearman")

```

### Things to consider

```{r}
lollipop <- .generate_lollipop(500)
plot(lollipop)
```

```{r}
stats::cor(lollipop)
energy::dcor(lollipop[,1],lollipop[,2])
```

## XI vs Spearman

### Linear
```{r}
lin <- gen_linear(200)
plot(lin)
```

```{r}
XICOR::calculateXI(lin[,1], lin[,2])
stats::cor(lin, method = "spearman")
```

### Quadratic

```{r}
XICOR::calculateXI(quadratic_1[,1], quadratic_1[,2])
stats::cor(quadratic_1, method = "spearman")
```

### Sine

```{r}
XICOR::calculateXI(sine[,1], sine[,2])
stats::cor(sine, method = "spearman")
```

## Hoeffding's D vs XI

### quadratic

```{r}
Hmisc::hoeffd(sine[,1], sine[,2])$D
XICOR::calculateXI(sine[,1], sine[,2])
```

```{r}
plot(quadratic_1)
```

```{r}
Hmisc::hoeffd(quadratic_1[,1], quadratic_1[,2])$D
XICOR::calculateXI(quadratic_1[,1], quadratic_1[,2])
```

### Quadratic with noise

```{r}
plot(quadratic2)
```

```{r}
Hmisc::hoeffd(quadratic2[,1], quadratic2[,2])$D
XICOR::calculateXI(quadratic2[,1], quadratic2[,2])
```

## Beta vs Spearman

### steep exponential 

```{r}
plot(power)
```

```{r}
stats::cor(power, method = "spearman")
VineCopula::BetaMatrix(power)
```

```{r}
gen_quadrant <- function(n){
  t(sapply(1:n, function(i){
    rand_int <- sample(1:4, 1)
    if (rand_int == 1){
      x <- stats::runif(1, min = 0, max = 3)
      y <- stats::runif(1, min = 0, max = 3)
      
    } else if (rand_int == 2){
      x <- stats::runif(1, min = 0, max = 4)
      y <- stats::runif(1, min = 10, max = 14)
      
    } else if (rand_int == 3){
      x <- stats::runif(1, min = 10, max = 14)
      y <- stats::runif(1, min = 0, max = 4)
      
    } else {
      x <- stats::runif(1, min = 10, max = 14)
      y <- stats::runif(1, min = 10, max = 14)
    }
    c(x,y)
  }))
}

quadrant <- gen_quadrant(exper_n)

mean(quadrant[, 1])
mean(quadrant[, 2])
plot(quadrant)
```

## Beta vs MI

```{r}
VineCopula::BetaMatrix(quadrant)
mi.empirical(entropy::discretize2d(as.matrix(quadrant[, 1]), as.matrix(quadrant[, 2]), numBins1 = 20, numBins2 = 20))
```


## Beta vs Kendall 

```{r}
plot(quadrant)
```

```{r}
VineCopula::BetaMatrix(quadrant)
stats::cor(quadrant, method = "kendall")
#minerva::mine(quadrant)$MIC
```


```{r}
plot(lin)
```

```{r}
VineCopula::BetaMatrix(lin)
stats::cor(lin, method = "kendall")
#minerva::mine(quadrant)$MIC
```

## MIC vs MI

```{r}
plot(quadratic_1)
```

```{r}
minerva::mine(quadratic_1)$MIC
mi.empirical(entropy::discretize2d(as.matrix(quadratic_1[, 1]), as.matrix(quadratic_1[, 2]), numBins1 = 10, numBins2 = 10))
```


# Explore more about the lollipop

```{r}
original <- .generate_lollipop
```

```{r}
set.seed(11)
lollipop <- original(500)
plot(lollipop)
```

```{r}
stats::cor(lollipop, method = "pearson")[1,2]
energy::dcor(lollipop[,1],lollipop[,2])
```

```{r}
XICOR::calculateXI(lollipop[,1], lollipop[,2])
stats::cor(lollipop, method = "spearman")[1,2]
```

```{r}
Hmisc::hoeffd(lollipop[,1], lollipop[,2])$D
XICOR::calculateXI(lollipop[,1], lollipop[,2])
```

```{r}
stats::cor(lollipop, method = "spearman")[1,2]
VineCopula::BetaMatrix(lollipop)[1,2]
```

```{r}
VineCopula::BetaMatrix(lollipop)[1,2]
stats::cor(lollipop, method = "kendall")[1,2]
```

```{r}
new_lollipop1 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:3, 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 1)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    
      # generate "bridge"
    } else if (k == 2){
      x <- stats::rnorm(1, mean = 1, sd = 0.5)
      y <- stats::rnorm(1, mean = 2, sd = 0.5)
      
    } else {
      # k == 3, generate "stick"
      x <- stats::rnorm(1, mean = 3, sd = 0.8)
      y <- x + stats::rnorm(1, mean = 1, sd = 0.5)
    } 
    
    c(x,y)
  }))
}
```

```{r}
set.seed(10)
new_pop1 <- new_lollipop1(500)
plot(new_pop1)
```

```{r}
stats::cor(new_pop1, method = "pearson")[1,2]
energy::dcor(new_pop1[,1],new_pop1[,2])
```

```{r}
XICOR::calculateXI(new_pop1[,1], new_pop1[,2])
stats::cor(new_pop1, method = "spearman")[1,2]
```

```{r}
Hmisc::hoeffd(new_pop1[,1], new_pop1[,2])$D
XICOR::calculateXI(new_pop1[,1], new_pop1[,2])
```

```{r}
stats::cor(new_pop1, method = "spearman")[1,2]
VineCopula::BetaMatrix(new_pop1)[1,2]
```

```{r}
VineCopula::BetaMatrix(new_pop1)[1,2]
stats::cor(new_pop1, method = "kendall")[1,2]
```

```{r}
set.seed(10)
new_lollipop2 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:2, 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 1)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } else {
      # k == 2, generate "stick"
      x <- stats::rnorm(1, mean = 1, sd = 0.8)
      y <- x + stats::rnorm(1, mean = 0.5, sd = 0.5)
    }
        
    c(x,y)
  }))
}
```

```{r}
new_pop2 <- new_lollipop2(500)
plot(new_pop2)
```

```{r}
stats::cor(new_pop2, method = "pearson")[1,2]
energy::dcor(new_pop2[,1],new_pop2[,2])
```

```{r}
XICOR::calculateXI(new_pop2[,1], new_pop2[,2])
stats::cor(new_pop2, method = "spearman")[1,2]
```

```{r}
Hmisc::hoeffd(new_pop2[,1], new_pop2[,2])$D
XICOR::calculateXI(new_pop2[,1], new_pop2[,2])
```

```{r}
stats::cor(new_pop2, method = "spearman")[1,2]
VineCopula::BetaMatrix(new_pop2)[1,2]
```

```{r}
VineCopula::BetaMatrix(new_pop2)[1,2]
stats::cor(new_pop2, method = "kendall")[1,2]
```

```{r}
set.seed(15)
new_lollipop3 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:2, 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 1)
      y <- stats::rnorm(1, mean = 0, sd = 1)
      
    } else {
      # k == 2, generate "stick"
      x <- stats::rnorm(1, mean = 3, sd = 0.5)
      y <- x + stats::rnorm(1, mean = 1, sd = 0.5)
    }
        
    c(x,y)
  }))
}
```

```{r}
new_pop3 <- new_lollipop3(500)
plot(new_pop3)
```

```{r}
stats::cor(new_pop3, method = "pearson")[1,2]
energy::dcor(new_pop3[,1],new_pop3[,2])
```

```{r}
XICOR::calculateXI(new_pop3[,1], new_pop3[,2])
stats::cor(new_pop3, method = "spearman")[1,2]
```

```{r}
Hmisc::hoeffd(new_pop3[,1], new_pop3[,2])$D
XICOR::calculateXI(new_pop3[,1], new_pop3[,2])
```

```{r}
stats::cor(new_pop3, method = "spearman")[1,2]
VineCopula::BetaMatrix(new_pop3)[1,2]
```

```{r}
VineCopula::BetaMatrix(new_pop3)[1,2]
stats::cor(new_pop3, method = "kendall")[1,2]
```

```{r}
set.seed(230)
new_lollipop4 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(c(1,2), 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 1)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } else {
      # k == 2, generate "stick"
      x <- stats::rnorm(1, mean = 1, sd = 0.8)
      y <- x + stats::rnorm(1, mean = 1, sd = 0.5)
    }
    
    c(x,y)
  }))
}
```

```{r}
new_pop4 <- new_lollipop4(500)
plot(new_pop4)
```

```{r}
stats::cor(new_pop4, method = "pearson")[1,2]
energy::dcor(new_pop4[,1],new_pop4[,2])
```

```{r}
XICOR::calculateXI(new_pop4[,1], new_pop4[,2])
stats::cor(new_pop4, method = "spearman")[1,2]
```

```{r}
Hmisc::hoeffd(new_pop4[,1], new_pop4[,2])$D
XICOR::calculateXI(new_pop4[,1], new_pop4[,2])
```

```{r}
stats::cor(new_pop4, method = "spearman")[1,2]
VineCopula::BetaMatrix(new_pop4)[1,2]
```

```{r}
VineCopula::BetaMatrix(new_pop4)[1,2]
stats::cor(new_pop4, method = "kendall")[1,2]
```