---
title: "Corpula_Celltype"
author: "Taewan Kim"
date: "1/18/2021"
output: html_document
---

# First cell type

```{r}
p <- 8
first_n <- 150
corpula_mean_first <- c(10, 0, 10, 0, 10, 0, 10, 0) # mu
cov_mat_first <- matrix(0, p, p); 
diag(cov_mat_first) <- c(20, 5, 20, 5, 20, 5, 20, 5)

norm_first <- MASS::mvrnorm(first_n, corpula_mean_first, cov_mat_first)
corpula_first <- norm_first

# nonparanormal transform
corpula_first <- apply(corpula_first, 2, function(x) {0.4 * sign(x) * abs(x)^1.6})

# this is the gaussian data we need to make nonparanormals
pairs(norm_first, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)

# this is the nonparanormal 
pairs(corpula_first, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)

```

# Second cell type

```{r}
second_n <- 200
corpula_mean_second <- c(0, 10, 0, 10,
                         0, 10, 0, 10) # mu

cov_mat_second <- matrix(0, p, p)
diag(cov_mat_second) <- c(5, 20, 5, 20, 5, 20, 5, 20) # Sigma


norm_second <- MASS::mvrnorm(second_n, corpula_mean_second, cov_mat_second)
corpula_second <- norm_second

# nonparanormal transform
corpula_second <- apply(corpula_second, 2, function(x) {0.4 * sign(x) * abs(x)^1.6})

# this is the gaussian data we need to make nonparanormals
pairs(norm_second, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)

# this is the nonparanormal 
pairs(corpula_second, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)
```

# Third cell type

```{r}
third_n <- 150
corpula_mean_third <- c(10, 0, 0, 10, 
                        8, 8, 10, 10)
cov_mat_third <- matrix(4, p, p);
diag(cov_mat_third) <- c(5, 10, 5, 10, 5, 10, 5, 10) # Sigma

cov_mat_third[5,6] <- 1.5; cov_mat_third[6,5] <- 1.5;
cov_mat_third[6,7] <- 5; cov_mat_third[7,6] <- 5;

#(1,3), (1,5), (1,7), (2,4), (2,6), (2,8), (3,5), (3,7), (4,6), (4,8), (5,7), (6,8)

norm_third <- MASS::mvrnorm(third_n, corpula_mean_third, cov_mat_third)
corpula_third <- norm_third

# nonparanormal transform
corpula_third <- apply(corpula_third, 2, function(x) {0.6 * sign(x) * abs(x)^1.8})

norm_expr <- MASS::mvrnorm(third_n, corpula_mean_third, cov_mat_third)


# this is the gaussian data we need to make nonparanormals
pairs(norm_third, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)

# this is the nonparanormal 
pairs(corpula_third, asp = T, pch = 16,  col = rgb(0.5,0.5,0.5,0.5), lower.panel = NULL)
```

# Combine the three cell types

```{r}
gen_dat <- rbind(cbind(corpula_first, rep(1, first_n)), 
                 cbind(corpula_second, rep(2, second_n)),
                 cbind(corpula_third, rep(3, third_n)))

pairs(gen_dat[, 1:8], asp = T, pch = 16,  col = gen_dat[, 9], lower.panel = NULL)
pairs(gen_dat[, 1:8], asp = T, pch = 16,  col = rgb(0.5, 0.5, 0.5, 0.5), lower.panel = NULL)


```

# 2 x 2 Example

```{r}
set.seed(10)
n <- 500
mean_vec_1 <- c(20,0)
cov_mat_1 <- matrix(c(100, 0,
                      0, 50), 2, 2)
####
mean_vec_2 <- c(0,20)
cov_mat_2 <- matrix(c(50, 0,
                      0, 100), 2, 2)

dat_1 <- MASS::mvrnorm(n, mu = mean_vec_1, Sigma = cov_mat_1)

dat_2 <- MASS::mvrnorm(n, mu = mean_vec_2, Sigma = cov_mat_2)

dat <- rbind(dat_1, dat_2)
# dat_3 <- MASS::mvrnorm(n, mu = c(0,0), Sigma = diag(2))
# dat <- rbind(dat_1, dat_2, dat_3)

# par(mar = c(0.5, 0.5, 0.5, 0.5))
plot(dat[,1], dat[,2], asp = T,
     pch = 16, col = rgb(0.5, 0.5, 0.5, 0.1))

dat_1 <- apply(dat_1, 2, function(x){x^2}) # copula-part (monotonic transformation)
dat_2 <- apply(dat_2, 2, function(x){x^2})

dat <- rbind(dat_1, dat_2)

plot(dat[,1], dat[,2], asp = T,
     pch = 16, col = rgb(0.5, 0.5, 0.5, 0.1))

```