---
title: "Lollipop_Explore2"
author: "Taewan Kim"
date: "4/15/2021"
output: 
    html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---

```{r}
library(reshape2) # melt function
library(ggplot2) # ggplot function
library(pcaPP) # Fast Kendall function
library(energy) # Distance Correlation
library(Hmisc) # Hoeffding's D measure
library(entropy) # Mutual Information
library(minerva) # Maximum Information Coefficient
library(XICOR) # Chatterjee's Coefficient
library(dHSIC) # Hilbert Schmidt Independence Criterion
library(VineCopula) # Blomqvist's Beta
library(zebu) # Normalized Mutual Information
```

```{r}
my_beta <- function(x, y){
    # following Blomqvist, N. (1950).  On a measure of dependence between two
    # random variables. The Annals of Mathematical Statistics, 21(4), 593-600.
    mx <- median(x); my <- median(y)
    n1 <- sum(x < mx & y > my) +  sum(x > mx & y < my)
    n2 <- sum(x < mx & y < my) +  sum(x > mx & y > my)
    
    return ((n1 - n2)/(n1 + n2))
 
}

my_XICOR <- function(x, y){
  return(max(XICOR::calculateXI(x,y), XICOR::calculateXI(y,x)))
}

get_measures <- function(dat){
  pearson_cor <- stats::cor(dat, method = "pearson")[1,2]
  spearman_cor <- stats::cor(dat, method = "spearman")[1,2]
  kendall_cor <- pcaPP::cor.fk(dat)[1,2]
  dist_cor <- energy::dcor(dat[,1], dat[,2])
  hoeff_cor <- Hmisc::hoeffd(dat[,1], dat[,2])$D[1,2]
  MI_cor <- (zebu::lassie(dat, continuous=c(1,2), breaks = 6, measure = "npmi"))$global
  MIC_cor <- minerva::mine(dat)$MIC[1,2]
  XICOR_cor <- my_XICOR(dat[,1], dat[,2])
  HSIC_cor <- dHSIC::dhsic(dat[,1], dat[, 2])$dHSIC
  beta_cor <- my_beta(dat[, 1], dat[, 2])
  return(c(pearson_cor, spearman_cor, kendall_cor, dist_cor, hoeff_cor,
           MI_cor, MIC_cor, XICOR_cor, HSIC_cor, beta_cor))
}
```

```{r}
new_lollipop1 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:3, 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 1)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    
      # generate "bridge"
    } else if (k == 2){
      x <- stats::rnorm(1, mean = 1, sd = 0.5)
      y <- stats::rnorm(1, mean = 2, sd = 0.5)
      
    } else {
      # k == 3, generate "stick"
      x <- stats::rnorm(1, mean = 3, sd = 0.8)
      y <- x + stats::rnorm(1, mean = 1, sd = 0.5)
    } 
    
    c(x,y)
  }))
}
```

```{r}
lollipop1 <- new_lollipop1(500)
plot(lollipop1)
```

```{r}
new_lollipop2 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:3, 1)
    
    # generate "ball"
    if(k == 1){
      x <- stats::rnorm(1, mean = 0, sd = 0.25)
      y <- stats::rnorm(1, mean = 0, sd = 0.5)
    
      # generate "small stick"
    } else if (k == 2){
      x <- stats::rnorm(1, mean = 1.5, sd = 0.8) - 0.5
      y <- stats::rnorm(1, mean = 0.5, sd = 0.5) + 0.5
      
    } else {
      # k == 3, generate "stick"
      x <- stats::rnorm(1, mean = 2.5, sd = 0.8) - 0.5
      y <- x + stats::rnorm(1, mean = 1, sd = 0.5) + 0.5
    } 
    
    c(x,y)
  }))
}

```

```{r}
lollipop2 <- new_lollipop2(500)
plot(lollipop2)
```

```{r}
new_lollipop3 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:12, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 4, sd = 2)
      y <- x + stats::rnorm(1, mean = 1, sd = 1)
      
    } else { # generate "ball"
      x <- stats::rnorm(1, mean = 0, sd = 0.5)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } 

    c(x,y)
  }))
}

```

```{r}
lollipop3 <- new_lollipop3(500)
plot(lollipop3)
```

```{r}
new_lollipop4 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:12, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 4, sd = 2)
      y <- 2 * x + stats::rnorm(1, mean = 1, sd = 1)
      
    } else { # generate "ball"
      x <- stats::rnorm(1, mean = 0, sd = 0.5)
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } 

    c(x,y)
  }))
}

```

```{r}
lollipop4 <- new_lollipop4(500)
plot(lollipop4)
```

```{r}
new_lollipop5 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:12, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 4, sd = 2)
      y <- x + stats::rnorm(1, mean = 1, sd = 1)
      
    } else if (k == 2) {
      y <- stats::rnorm(1, mean = 0, sd = 0.5)
      x <- y + stats::rnorm(1, mean = 2, sd = 2)
      
    } else { # generate "ball"
      if (k %in% 3:6){
        x <- stats::rnorm(1, mean = 0, sd = 0.5)
      } else if (k %in% 7:10){
        x <- stats::rnorm(1, mean = 0, sd = 0.3)
      } else {
        x <- stats::rnorm(1, mean = 0.2, sd = 0.3)
      }
      
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } 

    c(x,y)
  }))
}
```

```{r}
lollipop5 <- new_lollipop5(500)
plot(lollipop5)
```

```{r}
new_lollipop6 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:12, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 4, sd = 2)
      y <- x + stats::rnorm(1, mean = 1, sd = 1)
      
    } else if (k == 2) {
      y <- stats::rnorm(1, mean = 0, sd = 0.5)
      x <- y + stats::rnorm(1, mean = 2, sd = 2)
      
    } else { # generate "ball"
      if (k %in% 3:6){
        x <- stats::rnorm(1, mean = 0, sd = 0.5)
      } else if (k %in% 7:10){
        x <- stats::rnorm(1, mean = 0.5, sd = 0.3)
      } else {
        x <- stats::rnorm(1, mean = 0.2, sd = 0.3)
      }
      
      y <- stats::rnorm(1, mean = 0, sd = 1)
    } 

    c(x,y)
  }))
}

```


```{r}
lollipop6 <- new_lollipop6(500)
plot(lollipop6)
```

```{r}
new_lollipop7 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:6, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 4, sd = 2)
      y <- x + stats::rnorm(1, mean = 1, sd = 1)
      
    } else if (k == 2) {
      y <- stats::rnorm(1, mean = 0, sd = 0.5)
      x <- y + stats::rnorm(1, mean = 2, sd = 2)
      
    } else { # generate "ball"
      if (k %in% 3:4){
        x <- stats::rnorm(1, mean = 0, sd = 0.5)
        y <-stats::rnorm(1, mean = 0, sd = 0.5)
      } else if (k %in% 5:6){
        x <- stats::rnorm(1, mean = 1, sd = 0.5)
        y <- stats::rnorm(1, mean = 1.5, sd = 0.5)
      }
    } 

    c(x,y)
  }))
}

```

```{r}
lollipop7 <- new_lollipop7(500)
plot(lollipop7)
```

```{r}
new_lollipop8 <- function(n){
  t(sapply(1:n, function(i){
    # generate "cluster" assignment
    k <- sample(1:4, 1)

    if (k == 1) {
      # k == 1, generate "stick"
      x <- stats::rnorm(1, mean = 2, sd = 1)
      y <- 2 * x + stats::rnorm(1, mean = 3, sd = 2)
      
    } else if (k == 2) {
      y <- stats::rnorm(1, mean = 1, sd = 0.5)
      x <- y + stats::rnorm(1, mean = 1, sd = 2)
      
    } else { # generate "ball"
      if (k == 3){
        x <- stats::rnorm(1, mean = 0, sd = 0.5)
        y <- stats::rnorm(1, mean = 0.5, sd = 0.5)
      } else {
        x <- stats::rnorm(1, mean = 1, sd = 0.5)
        y <- stats::rnorm(1, mean = 1.5, sd = 0.5)
      }
    } 

    c(x,y)
  }))
}

```

```{r}
lollipop8 <- new_lollipop8(500)
plot(lollipop8)
```



```{r}
all_corr <- c()
lollipop_lst <- list(lollipop1, lollipop2, lollipop3, lollipop4,
                  lollipop5, lollipop6, lollipop7, lollipop8)

for (i in 1:8) {
  cur_corr <- get_measures(lollipop_lst[[i]])
  all_corr <- rbind(all_corr, cur_corr)
}

rownames(all_corr) <- 1:8
colnames(all_corr) <- c("pearson", "spearman", "kendall", "dist_cor", "hoeff_D",
                        "MI", "MIC", "XICOR", "HSIC", "Blomq_beta")

all_corr
```

```{r}
plot(lollipop_lst[[1]], 
      main = paste(paste0("Pearson of ", round(all_corr[1, 1], 3)),
                   " ",
                   paste0("Spearman of ", round(all_corr[1, 2], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[1, 4], 3)),
                   "\n",
                   paste0("Hoeff D of", round(all_corr[1,5], 3))))
```

```{r}
plot(lollipop_lst[[2]], 
      main = paste(paste0("Pearson of ", round(all_corr[2, 1], 3)),
                   " ",
                   paste0("Spearman of ", round(all_corr[2, 2], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[2, 4], 3)),
                   "\n",
                   paste0("Hoeff D of ", round(all_corr[2,5], 3)),
                   " ",
                   paste0("Mutual Info of ", round(all_corr[2,6], 3))))

```


```{r}
plot(lollipop_lst[[3]], 
      main = paste(paste0("Pearson of ", round(all_corr[3, 1], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[3, 4], 3)),
                   "\n",
                   paste0("Spearman of ", round(all_corr[3, 2], 3)),
                   " ",
                   paste0("Hoeff D of ", round(all_corr[3, 5], 3)),
                   " ",
                   paste0("XICOR of ", round(all_corr[3, 8], 3)),
                   " ",
                   paste0("Beta of ", round(all_corr[3, 10], 3))
                   ))

```


```{r}
plot(lollipop_lst[[4]], 
      main = paste(paste0("Pearson of ", round(all_corr[4, 1], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[4, 4], 3)),
                   "\n",
                   paste0("Spearman of ", round(all_corr[4, 2], 3)),
                   " ",
                   paste0("Hoeff D of ", round(all_corr[4, 5], 3)),
                   " ",
                   paste0("XICOR of ", round(all_corr[4, 8], 3)),
                   " ",
                   paste0("Beta of ", round(all_corr[4, 10], 3))
                   ))

```

```{r}
plot(lollipop_lst[[5]], 
      main = paste(paste0("Pearson of ", round(all_corr[5, 1], 3)),
                   "\n",
                   paste0("Spearman of ", round(all_corr[5, 2], 3)),
                   " ",
                   paste0("MIC of ", round(all_corr[5, 7], 3)),
                   " ",
                   paste0("XICOR of ", round(all_corr[5, 8], 3))
                   ))

```

```{r}
plot(lollipop_lst[[6]], 
      main = paste(paste0("Pearson of ", round(all_corr[6, 1], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[6, 4], 3)),
                   "\n",
                   paste0("Spearman of ", round(all_corr[6, 2], 3)),
                   " ",
                   paste0("Mutual Info of ", round(all_corr[6, 6], 3)),
                   " ",
                   paste0("XICOR of ", round(all_corr[6, 8], 3))
                   ))

```

```{r}
plot(lollipop_lst[[7]], 
      main = paste(paste0("Pearson of ", round(all_corr[7, 1], 3)),
                   " ",
                   paste0("Dist Cor of ", round(all_corr[7, 4], 3)),
                   "\n",
                   paste0("Hoeff D of ", round(all_corr[7, 5], 3)),
                   " ",
                   paste0("Mutual Info of ", round(all_corr[7, 6], 3)),
                   " ",
                   paste0("XICOR of ", round(all_corr[7, 8], 3))
                   ))

```

```{r}
# gaussian_kernel <- function(u){
#   1/sqrt(2*pi) * exp(-1/2 * u^2)
# }
# 
# x <- lollipop1[,1]; y <- lollipop1[,1];
# bandwidth <- 1
# 
X <- list(x, y)
X <- split(X, rep(1:ncol(X), each = nrow(X)))

# 
d <- length(X)
for(j in 1:d){
  if(is.matrix(X[[j]])==FALSE){
    X[[j]] <- as.matrix(X[[j]])
  }
}
# 
# len <- nrow(X[[1]])
# kernel <- "gaussian"
# 
# custom_grammat <- function(x,fun){
#   KX <- matrix(nrow=len,ncol=len)
#   for (i in 1:len){
#     for (j in i:len){
#       KX[i,j] <- match.fun(fun)(x[i,],x[j,])
#       KX[j,i] <- KX[i,j]
#     }
#   }
#   return(KX)
#     }
# 
# K <- vector("list", d)
# 
# for(j in 1:d){
#   if(kernel[j]=="gaussian"){
#     bandwidth[j] <- median_bandwidth(X[[j]])
#     K[[j]] <- gaussian_grammat_rcpp(X[[j]],bandwidth[j],len,ncol(X[[j]]))
#   }
# }



dHSIC::dhsic(X = x, Y =y, kernel = "gaussian")
dHSIC::dhsic(cbind(x, y), kernel = "gaussian", matrix.input = T)
```